### ISSUE TITLE
Kappa in "Etymology" section

### ISSUE THREAD

**Issue by johnfactotum** [standardebooks/herman-melville_moby-dick#12]
**Describe the bug**

In the *Etymology* section, the Greek word for whale is `ϰητος`, spelled with `ϰ` (U+03F0).

**Expected behavior**

It should use either `Κ` (U+039A) or `κ` (U+03BA).

Currently, the word is in small caps, same as the rest of the foreign words in the table. In this case it should probably use the uppercase `Κ`.

But to make it more in line with the original (https://commons.wikimedia.org/w/index.php?title=File%3AMoby-Dick_%281851%29_US_edition.djvu&page=17), the word would be set in italics with lowercase `κ` (which was probably why it was written with `ϰ`, which looks like an italicized `κ`).

**Additional context**

According to The Unicode Standard, Version 15.0, Section 7.2 (page 307)

> In contrast, U+03D0 greek beta symbol, U+03D1 greek theta symbol, U+03D2 greek upsilon with hook symbol, U+03D5 greek phi symbol, U+03F0 greek kappa symbol, U+03F1 greek rho symbol, U+03F4 greek capital theta symbol, U+03F5 greek lunate epsilon symbol, and U+03F6 greek reversed lunate epsilon symbol should be used only in mathematical formulas—never in Greek text. If positional or other shape differences are desired for these characters, they should be implemented by a font or rendering engine.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
